/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package conectar;

import java.sql.Connection;





/**
 *
 * @author ivamar
 */
public class VentanaSeleccionDatabases extends javax.swing.JFrame {
 private Connection con;
    /**
     * Creates new form VentanaInsercion
     * @param con
     */
    

    public VentanaSeleccionDatabases(Connection con) {
        this.con=con;
        initComponents();
    }

    private VentanaSeleccionDatabases() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        PELICULAS = new javax.swing.JButton();
        MUSICA = new javax.swing.JButton();
        SOCIOS = new javax.swing.JButton();
        PRESTAMOS = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(238, 245, 219));
        jPanel1.setForeground(new java.awt.Color(238, 245, 219));

        jLabel2.setFont(new java.awt.Font("Carlito", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(79, 99, 103));
        jLabel2.setText("Hecho por Iván Torres Marcos");

        jLabel1.setFont(new java.awt.Font("Carlito", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(79, 99, 103));
        jLabel1.setText("Seleccione la tabla de la base de datos que quiera modificar:");

        PELICULAS.setBackground(new java.awt.Color(79, 99, 103));
        PELICULAS.setFont(new java.awt.Font("Carlito", 1, 13)); // NOI18N
        PELICULAS.setForeground(new java.awt.Color(184, 216, 216));
        PELICULAS.setText("PELÍCULAS");
        PELICULAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PELICULASActionPerformed(evt);
            }
        });

        MUSICA.setBackground(new java.awt.Color(79, 99, 103));
        MUSICA.setFont(new java.awt.Font("Carlito", 1, 13)); // NOI18N
        MUSICA.setForeground(new java.awt.Color(184, 216, 216));
        MUSICA.setText("MÚSICA");
        MUSICA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MUSICAActionPerformed(evt);
            }
        });

        SOCIOS.setBackground(new java.awt.Color(79, 99, 103));
        SOCIOS.setFont(new java.awt.Font("Carlito", 1, 13)); // NOI18N
        SOCIOS.setForeground(new java.awt.Color(184, 216, 216));
        SOCIOS.setText("SOCIOS");
        SOCIOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SOCIOSActionPerformed(evt);
            }
        });

        PRESTAMOS.setBackground(new java.awt.Color(79, 99, 103));
        PRESTAMOS.setFont(new java.awt.Font("Carlito", 1, 13)); // NOI18N
        PRESTAMOS.setForeground(new java.awt.Color(184, 216, 216));
        PRESTAMOS.setText("PRÉSTAMOS");
        PRESTAMOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRESTAMOSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 26, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PELICULAS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SOCIOS, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PRESTAMOS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MUSICA, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PELICULAS)
                    .addComponent(MUSICA))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SOCIOS)
                    .addComponent(PRESTAMOS))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PELICULASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PELICULASActionPerformed
        // TODO add your handling code here:
         PELICULAS peliculas = new PELICULAS(con);
            peliculas.setVisible(true);
    }//GEN-LAST:event_PELICULASActionPerformed

    private void SOCIOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SOCIOSActionPerformed
        // TODO add your handling code here:
         SOCIOSO socios = new SOCIOSO(con);
            socios.setVisible(true);
    }//GEN-LAST:event_SOCIOSActionPerformed

    private void MUSICAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MUSICAActionPerformed
        // TODO add your handling code here:
         MUSICA musica = new MUSICA(con);
            musica.setVisible(true);
    }//GEN-LAST:event_MUSICAActionPerformed

    private void PRESTAMOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRESTAMOSActionPerformed
        // TODO add your handling code here:
         PRESTAMOS prestamos = new PRESTAMOS(con);
            prestamos.setVisible(true);
    }//GEN-LAST:event_PRESTAMOSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaSeleccionDatabases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaSeleccionDatabases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaSeleccionDatabases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaSeleccionDatabases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaSeleccionDatabases().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MUSICA;
    private javax.swing.JButton PELICULAS;
    private javax.swing.JButton PRESTAMOS;
    private javax.swing.JButton SOCIOS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
