/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package conectar;

import java.sql.Connection;





/**
 *
 * @author ivamar
 */
public class VentanaSeleccionDatabases extends javax.swing.JFrame {
 private Connection con;
    /**
     * Creates new form VentanaInsercion
     * @param con
     */
    

    public VentanaSeleccionDatabases(Connection con) {
        this.con=con;
        initComponents();
        setTitle("SELECCIÓN 🎉");
    }

    private VentanaSeleccionDatabases() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        PELICULAS = new javax.swing.JButton();
        MUSICA = new javax.swing.JButton();
        SOCIOS = new javax.swing.JButton();
        PRESTAMOS = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Carlito", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ponme un 10 Carmen <3");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 560, -1, -1));

        jLabel1.setFont(new java.awt.Font("Carlito", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(79, 99, 103));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seleccionelatabla.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 14, -1, -1));

        PELICULAS.setBackground(new java.awt.Color(204, 204, 204));
        PELICULAS.setFont(new java.awt.Font("Carlito", 1, 18)); // NOI18N
        PELICULAS.setForeground(new java.awt.Color(0, 0, 0));
        PELICULAS.setText("PELÍCULAS");
        PELICULAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PELICULASActionPerformed(evt);
            }
        });
        jPanel1.add(PELICULAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 171, 73));

        MUSICA.setBackground(new java.awt.Color(204, 204, 204));
        MUSICA.setFont(new java.awt.Font("Carlito", 1, 18)); // NOI18N
        MUSICA.setForeground(new java.awt.Color(0, 0, 0));
        MUSICA.setText("MÚSICA");
        MUSICA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MUSICAActionPerformed(evt);
            }
        });
        jPanel1.add(MUSICA, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 163, 73));

        SOCIOS.setBackground(new java.awt.Color(204, 204, 204));
        SOCIOS.setFont(new java.awt.Font("Carlito", 1, 18)); // NOI18N
        SOCIOS.setForeground(new java.awt.Color(0, 0, 0));
        SOCIOS.setText("SOCIOS");
        SOCIOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SOCIOSActionPerformed(evt);
            }
        });
        jPanel1.add(SOCIOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 171, 74));

        PRESTAMOS.setBackground(new java.awt.Color(204, 204, 204));
        PRESTAMOS.setFont(new java.awt.Font("Carlito", 1, 18)); // NOI18N
        PRESTAMOS.setForeground(new java.awt.Color(0, 0, 0));
        PRESTAMOS.setText("PRÉSTAMOS");
        PRESTAMOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRESTAMOSActionPerformed(evt);
            }
        });
        jPanel1.add(PRESTAMOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 440, 163, 74));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carita.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 99, 93));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/estrellita.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 153, 150));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/estrellita.png"))); // NOI18N
        jLabel5.setText("jLabel4");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 350, 153, 150));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carita.png"))); // NOI18N
        jLabel6.setText("jLabel3");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 99, 93));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carita.png"))); // NOI18N
        jLabel7.setText("jLabel3");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 470, 99, 93));

        jLabel8.setFont(new java.awt.Font("Carlito", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Hecho por Iván Torres Marcos");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 560, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PELICULASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PELICULASActionPerformed
        // TODO add your handling code here:
         PELICULAS peliculas = new PELICULAS(con);
            peliculas.setVisible(true);
    }//GEN-LAST:event_PELICULASActionPerformed

    private void SOCIOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SOCIOSActionPerformed
        // TODO add your handling code here:
         SOCIOSO socios = new SOCIOSO(con);
            socios.setVisible(true);
    }//GEN-LAST:event_SOCIOSActionPerformed

    private void MUSICAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MUSICAActionPerformed
        // TODO add your handling code here:
         MUSICA musica = new MUSICA(con);
            musica.setVisible(true);
    }//GEN-LAST:event_MUSICAActionPerformed

    private void PRESTAMOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRESTAMOSActionPerformed
        // TODO add your handling code here:
         PRESTAMOS prestamos = new PRESTAMOS(con);
            prestamos.setVisible(true);
    }//GEN-LAST:event_PRESTAMOSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaSeleccionDatabases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaSeleccionDatabases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaSeleccionDatabases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaSeleccionDatabases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaSeleccionDatabases().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MUSICA;
    private javax.swing.JButton PELICULAS;
    private javax.swing.JButton PRESTAMOS;
    private javax.swing.JButton SOCIOS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
